package com.github.rafaelsantos.hogwarts.model.vo.statics;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 15 21:49:20 BRT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StaticYearViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public StaticYearViewImpl() {
    }
}

